/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#f9f9ff",
        "on-secondary-container": "#663500",
        "on-tertiary-container": "#b87500",
        "on-primary-fixed": "#131b2e",
        "on-secondary-fixed": "#2f1500",
        "on-surface": "#111c2d",
        "error": "#ba1a1a",
        "surface": "#f9f9ff",
        "on-primary": "#ffffff",
        "surface-container-highest": "#d8e3fb",
        "surface-dim": "#cfdaf2",
        "primary-fixed": "#dae2fd",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        "on-background": "#111c2d",
        "secondary": "#904d00",
        "on-tertiary-fixed-variant": "#653e00",
        "on-tertiary-fixed": "#2a1700",
        "tertiary": "#000000",
        "tertiary-fixed": "#ffddb8",
        "on-primary-container": "#7c839b",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#ffdcc3",
        "primary-fixed-dim": "#bec6e0",
        "secondary-fixed-dim": "#ffb77d",
        "inverse-surface": "#263143",
        "primary-container": "#131b2e",
        "surface-container": "#e7eeff",
        "surface-variant": "#d8e3fb",
        "inverse-on-surface": "#ecf1ff",
        "primary": "#000000",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#fe932c",
        "outline": "#76777d",
        "tertiary-fixed-dim": "#ffb95f",
        "on-error": "#ffffff",
        "surface-container-low": "#f0f3ff",
        "inverse-primary": "#bec6e0",
        "surface-container-high": "#dee8ff",
        "on-primary-fixed-variant": "#3f465c",
        "on-secondary-fixed-variant": "#6e3900",
        "tertiary-container": "#2a1700",
        "outline-variant": "#c6c6cd",
        "error-container": "#ffdad6",
        "background": "#f9f9ff",
        "surface-tint": "#565e74",
        "on-surface-variant": "#45464d",
        "tactile-slate": "#0F172A",
        "tactile-amber": "#fe932c",
        "tactile-yellow": "#f59e0b"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-md": "1.25rem",
        "margin-mobile": "1.25rem",
        "space-xl": "3rem",
        "space-sm": "0.75rem",
        "space-lg": "2rem",
        "space-xs": "0.5rem",
        "gutter-mobile": "1rem",
        "gutter": "1.5rem",
        "margin": "2rem"
      },
      fontFamily: {
        sans: ["'Atkinson Hyperlegible Next'", "'Atkinson Hyperlegible'", "system-ui", "sans-serif"]
      }
    },
  },
  plugins: [],
};
